-- 0001_core: tenancy, sources, raw vault, double-entry ledger, evidence,
-- review, and audit tables.
--
-- Portability: this migration uses only the SQL subset shared by SQLite (local
-- / self-hosted) and PostgreSQL (hosted cloud). Identifiers and timestamps are
-- TEXT (UUIDs / ISO-8601), JSON payloads are TEXT, monetary amounts are decimal
-- strings in TEXT, and booleans are INTEGER 0/1. Primary keys are generated by
-- the application, not the database.
--
-- Tenant isolation: every workspace-owned child references its parent by a
-- composite (workspace_id, parent_id) foreign key against a UNIQUE
-- (workspace_id, id) on the parent, so a row can never reference a parent that
-- belongs to a different workspace.

-- Tenancy ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
  id          TEXT PRIMARY KEY,
  email       TEXT NOT NULL UNIQUE,
  created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS workspaces (
  id          TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  created_at  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS workspace_members (
  workspace_id  TEXT NOT NULL REFERENCES workspaces(id),
  user_id       TEXT NOT NULL REFERENCES users(id),
  role          TEXT NOT NULL,
  created_at    TEXT NOT NULL,
  PRIMARY KEY (workspace_id, user_id)
);

-- Sources ---------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS sources (
  id            TEXT PRIMARY KEY,
  workspace_id  TEXT NOT NULL REFERENCES workspaces(id),
  kind          TEXT NOT NULL,
  display_name  TEXT NOT NULL,
  status        TEXT NOT NULL,
  created_at    TEXT NOT NULL,
  UNIQUE (workspace_id, id)
);

CREATE INDEX IF NOT EXISTS idx_sources_workspace ON sources(workspace_id);

-- Encrypted credential references. Never store plaintext secrets here; this row
-- holds a reference resolved by the secret store, plus non-secret metadata.
CREATE TABLE IF NOT EXISTS source_credentials (
  id            TEXT PRIMARY KEY,
  workspace_id  TEXT NOT NULL REFERENCES workspaces(id),
  source_id     TEXT NOT NULL,
  secret_ref    TEXT NOT NULL,
  created_at    TEXT NOT NULL,
  FOREIGN KEY (workspace_id, source_id) REFERENCES sources(workspace_id, id)
);

CREATE TABLE IF NOT EXISTS source_sync_runs (
  id            TEXT PRIMARY KEY,
  workspace_id  TEXT NOT NULL REFERENCES workspaces(id),
  source_id     TEXT NOT NULL,
  status        TEXT NOT NULL,
  started_at    TEXT NOT NULL,
  finished_at   TEXT,
  error_json    TEXT,
  FOREIGN KEY (workspace_id, source_id) REFERENCES sources(workspace_id, id)
);

CREATE INDEX IF NOT EXISTS idx_sync_runs_source ON source_sync_runs(source_id);

-- Append-only raw source vault. Rows are immutable; corrections append a new
-- row that references the superseded one.
CREATE TABLE IF NOT EXISTS raw_source_records (
  id                    TEXT PRIMARY KEY,
  workspace_id          TEXT NOT NULL REFERENCES workspaces(id),
  source_id             TEXT NOT NULL,
  external_id           TEXT,
  record_type           TEXT NOT NULL,
  payload_json          TEXT NOT NULL,
  payload_hash          TEXT NOT NULL,
  observed_at           TEXT NOT NULL,
  supersedes_record_id  TEXT,
  created_at            TEXT NOT NULL,
  UNIQUE (workspace_id, id),
  FOREIGN KEY (workspace_id, source_id) REFERENCES sources(workspace_id, id),
  FOREIGN KEY (workspace_id, supersedes_record_id) REFERENCES raw_source_records(workspace_id, id)
);

CREATE INDEX IF NOT EXISTS idx_raw_records_source ON raw_source_records(source_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_raw_records_dedup
  ON raw_source_records(workspace_id, source_id, payload_hash);

-- Double-entry ledger ---------------------------------------------------------

CREATE TABLE IF NOT EXISTS ledger_accounts (
  id                TEXT PRIMARY KEY,
  workspace_id      TEXT NOT NULL REFERENCES workspaces(id),
  path              TEXT NOT NULL,
  kind              TEXT NOT NULL,
  commodity         TEXT,
  receipt_required  INTEGER NOT NULL DEFAULT 0 CHECK (receipt_required IN (0, 1)),
  created_at        TEXT NOT NULL,
  UNIQUE (workspace_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_accounts_path ON ledger_accounts(workspace_id, path);

CREATE TABLE IF NOT EXISTS ledger_transactions (
  id            TEXT PRIMARY KEY,
  workspace_id  TEXT NOT NULL REFERENCES workspaces(id),
  booked_on     TEXT NOT NULL,
  description   TEXT NOT NULL,
  review_state  TEXT NOT NULL,
  created_at    TEXT NOT NULL,
  UNIQUE (workspace_id, id)
);

CREATE INDEX IF NOT EXISTS idx_tx_workspace_date ON ledger_transactions(workspace_id, booked_on);

CREATE TABLE IF NOT EXISTS ledger_postings (
  id              TEXT PRIMARY KEY,
  workspace_id    TEXT NOT NULL REFERENCES workspaces(id),
  transaction_id  TEXT NOT NULL,
  account_id      TEXT NOT NULL,
  amount          TEXT NOT NULL,
  commodity       TEXT NOT NULL,
  memo            TEXT,
  FOREIGN KEY (workspace_id, transaction_id) REFERENCES ledger_transactions(workspace_id, id),
  FOREIGN KEY (workspace_id, account_id) REFERENCES ledger_accounts(workspace_id, id)
);

CREATE INDEX IF NOT EXISTS idx_postings_tx ON ledger_postings(transaction_id);
CREATE INDEX IF NOT EXISTS idx_postings_account ON ledger_postings(account_id);

-- Evidence, review, audit -----------------------------------------------------
-- These reference records polymorphically (from_type/from_id, target_type/...),
-- so they cannot use SQL foreign keys; the application enforces workspace
-- scoping on read/write.

CREATE TABLE IF NOT EXISTS evidence_links (
  id            TEXT PRIMARY KEY,
  workspace_id  TEXT NOT NULL REFERENCES workspaces(id),
  from_type     TEXT NOT NULL,
  from_id       TEXT NOT NULL,
  to_type       TEXT NOT NULL,
  to_id         TEXT NOT NULL,
  kind          TEXT NOT NULL,
  notes         TEXT,
  created_at    TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_evidence_from ON evidence_links(workspace_id, from_type, from_id);
CREATE INDEX IF NOT EXISTS idx_evidence_to ON evidence_links(workspace_id, to_type, to_id);

CREATE TABLE IF NOT EXISTS review_events (
  id            TEXT PRIMARY KEY,
  workspace_id  TEXT NOT NULL REFERENCES workspaces(id),
  target_type   TEXT NOT NULL,
  target_id     TEXT NOT NULL,
  from_state    TEXT NOT NULL,
  to_state      TEXT NOT NULL,
  actor         TEXT NOT NULL,
  notes         TEXT,
  created_at    TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_review_target ON review_events(workspace_id, target_type, target_id);

CREATE TABLE IF NOT EXISTS audit_events (
  id            TEXT PRIMARY KEY,
  workspace_id  TEXT NOT NULL REFERENCES workspaces(id),
  action        TEXT NOT NULL,
  actor         TEXT NOT NULL,
  target_type   TEXT,
  target_id     TEXT,
  metadata_json TEXT,
  created_at    TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_workspace ON audit_events(workspace_id, created_at);
